name: Run Build

on: [push]

jobs:
  create_env:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./create-env
  build:
    runs-on: ubuntu-latest
    environment: test
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'
      - uses: actions/cache@v2
        with:
          path: |
            .next/cache
            .next/dist
          key: ${{ runner.os }}-nextjs-build-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-build-
      # call the create-env yaml action from the .github/workflows folder
      - run: yarn install --frozen-lockfile
      - run: npx prisma generate
      - run: yarn build

      # - name: E2E 🛩
      #   run:
      #     yarn start-server-and-test 'yarn build-start' http://localhost:3000 'yarn cypress run --record --key ${{
      #     secrets.CYPRESS_RECORD_KEY }}'
